ShopTARge22/Models/RealEstates/RealEstateCreateUpdateViewModel.cs
using ShopTARge22.Models.Spaceships;

namespace ShopTARge22.Models.RealEstates
{
    public class RealEstateCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public string Address { get; set; }
        public float SizeSqrM { get; set; }
        public int RoomCount { get; set; }
        public int Floor { get; set; }
        public string BuildingType { get; set; }
        public DateTime BuiltInYear { get; set; }

        public List<IFormFile> Files { get; set; }
        public List<RealEstateImageViewModel> Image { get; set; } 
            = new List<RealEstateImageViewModel>();

        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

ShopTARge22/Models/RealEstates/RealEstateDeleteViewModel.cs
using ShopTARge22.Models.Spaceships;

namespace ShopTARge22.Models.RealEstates
{
    public class RealEstateDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string Address { get; set; }
        public float SizeSqrM { get; set; }
        public int RoomCount { get; set; }
        public int Floor { get; set; }
        public string BuildingType { get; set; }
        public DateTime BuiltInYear { get; set; }

        public List<RealEstateImageViewModel> Image { get; set; }
            = new List<RealEstateImageViewModel>();

        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

ShopTARge22/Models/RealEstates/RealEstateDetailsViewModel.cs
namespace ShopTARge22.Models.RealEstates
{
    public class RealEstateDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string Address { get; set; }
        public float SizeSqrM { get; set; }
        public int RoomCount { get; set; }
        public int Floor { get; set; }
        public string BuildingType { get; set; }
        public DateTime BuiltInYear { get; set; }

        public List<RealEstateImageViewModel> Image { get; set; } 
            = new List<RealEstateImageViewModel>();

        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

ShopTARge22/Models/RealEstates/RealEstateImageViewModel.cs
namespace ShopTARge22.Models.RealEstates
{
    public class RealEstateImageViewModel
    {
        public Guid ImageId { get; set; }
        public string ImageTitle { get; set; }
        public byte[] ImageData { get; set; }
        public string Image { get; set; }
        public Guid? RealEstateId { get; set; }
    }
}

ShopTARge22/Models/RealEstates/RealEstateIndexViewModel.cs
namespace ShopTARge22.Models.RealEstates
{
    public class RealEstateIndexViewModel
    {
        public Guid? Id { get; set; }
        public string Address { get; set; }
        public float SizeSqrM { get; set; }
        public int RoomCount { get; set; }
        public int Floor { get; set; }
        public string BuildingType { get; set; }
        public DateTime BuiltInYear { get; set; }

        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

ShopTARge22/Models/Spaceships/ImageViewModel.cs
namespace ShopTARge22.Models.Spaceships
{
    public class ImageViewModel
    {
        public Guid ImageId { get; set; }
        public string FilePath { get; set; }
        public Guid SpaceshipId { get; set; }
    }
}

ShopTARge22/Controllers/RealEstatesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopTARge22.Core.Dto;
using ShopTARge22.Core.ServiceInterface;
using ShopTARge22.Data;
using ShopTARge22.Models.RealEstates;
using static System.Net.Mime.MediaTypeNames;

namespace ShopTARge22.Controllers
{
    public class RealEstatesController : Controller
    {
        private readonly ShopTARge22Context _context;
        private readonly IRealEstatesServices _realEstatesServices;

        public RealEstatesController
            (
                ShopTARge22Context context,
                IRealEstatesServices realEstates
            )
        {
            _context = context;
            _realEstatesServices = realEstates;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var result = _context.RealEstates
                .OrderByDescending(y => y.CreatedAt)
                .Select(x => new RealEstateIndexViewModel
                {
                    Id = x.Id,
                    Address = x.Address,
                    BuildingType = x.BuildingType,
                    RoomCount = x.RoomCount,
                    SizeSqrM = x.SizeSqrM
                });

            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var realEstate = await _realEstatesServices.DetailsAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            var photos = await _context.FileToDatabases
                .Where(x => x.RealEstateId == id)
                .Select(y => new RealEstateImageViewModel
                {
                    RealEstateId = y.Id,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();

            var vm = new RealEstateDetailsViewModel();

            vm.Id = realEstate.Id;
            vm.Address = realEstate.Address;
            vm.SizeSqrM = realEstate.SizeSqrM;
            vm.RoomCount = realEstate.RoomCount;
            vm.Floor = realEstate.Floor;
            vm.BuildingType = realEstate.BuildingType;
            vm.BuiltInYear = realEstate.BuiltInYear;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.UpdatedAt = realEstate.UpdatedAt;
            vm.Image.AddRange(photos);

            return View(vm);
        }

        [HttpGet]
        public IActionResult Create()
        {
            RealEstateCreateUpdateViewModel vm = new();

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Create(RealEstateCreateUpdateViewModel vm)
        {
            var dto = new RealEstateDto()
            {
                Id = vm.Id,
                Address = vm.Address,
                SizeSqrM = vm.SizeSqrM,
                RoomCount = vm.RoomCount,
                Floor = vm.Floor,
                BuildingType = vm.BuildingType,
                BuiltInYear = vm.BuiltInYear,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = vm.UpdatedAt,
                Files = vm.Files,
                Image = vm.Image
                    .Select(x => new FileToDatabaseDto
                    {
                        Id = x.ImageId,
                        ImageData = x.ImageData,
                        ImageTitle = x.ImageTitle,
                        RealEstateId = x.RealEstateId
                    }).ToArray()
            };

            var result = await _realEstatesServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var realEstate = await _realEstatesServices.DetailsAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            var photos = await _context.FileToDatabases
                .Where(x => x.RealEstateId == id)
                .Select(y => new RealEstateImageViewModel
                {
                    RealEstateId = y.Id,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();

            var vm = new RealEstateCreateUpdateViewModel();

            vm.Id = realEstate.Id;
            vm.Address = realEstate.Address;
            vm.SizeSqrM = realEstate.SizeSqrM;
            vm.RoomCount = realEstate.RoomCount;
            vm.Floor = realEstate.Floor;
            vm.BuildingType = realEstate.BuildingType;
            vm.BuiltInYear = realEstate.BuiltInYear;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.UpdatedAt = realEstate.UpdatedAt;
            vm.Image.AddRange(photos);


            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(RealEstateCreateUpdateViewModel vm)
        {

            var dto = new RealEstateDto()
            {
                Id = vm.Id,
                Address = vm.Address,
                SizeSqrM = vm.SizeSqrM,
                RoomCount = vm.RoomCount,
                Floor = vm.Floor,
                BuildingType = vm.BuildingType,
                BuiltInYear = vm.BuiltInYear,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = vm.UpdatedAt,
                Files = vm.Files,
                Image = vm.Image
                    .Select(x => new FileToDatabaseDto
                    {
                        Id = x.ImageId,
                        ImageData = x.ImageData,
                        ImageTitle = x.ImageTitle,
                        RealEstateId = x.RealEstateId,
                    }).ToArray()
            };

            var result = await _realEstatesServices.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var realEstate = await _realEstatesServices.DetailsAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            var photos = await _context.FileToDatabases
                .Where(x => x.RealEstateId == id)
                .Select(y => new RealEstateImageViewModel
                {
                    RealEstateId = y.Id,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();

            var vm = new RealEstateDeleteViewModel();

            vm.Id = realEstate.Id;
            vm.Address = realEstate.Address;
            vm.SizeSqrM = realEstate.SizeSqrM;
            vm.RoomCount = realEstate.RoomCount;
            vm.Floor = realEstate.Floor;
            vm.BuildingType = realEstate.BuildingType;
            vm.BuiltInYear = realEstate.BuiltInYear;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.UpdatedAt = realEstate.UpdatedAt;
            vm.Image.AddRange(photos);

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var realEstateId = await _realEstatesServices.Delete(id);

            if (realEstateId == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ShopTARge22/Views/RealEstates/CreateUpdate.cshtml
@model ShopTARge22.Models.RealEstates.RealEstateCreateUpdateViewModel

@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Create</h1>
}


<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="UpdatedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="Address" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Address" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Size m2</label>
            <div class="col-sm-10">
                <input asp-for="SizeSqrM" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="RoomCount" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="RoomCount" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Floor" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Floor" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="BuildingType" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="BuiltInYear" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="BuiltInYear" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Files" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-5">
                <div class="custom-file">
                    <input class="form-control custom-file-input" asp-for="Files" multiple type="file" />
                    <label class="custom-file-label">Choose file...</label>
                </div>
            </div>
        </div>
        <hr />

        <div>
            @foreach (var images in Model.Image)
            {
                <partial name="_Images" model="images" />
            }
        </div>
        <hr />

        @if (Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="realestates" type="submit" class="btn btn-primary" value="Update" />
        }
        else
        {
            <input asp-action="create" asp-controller="realestates" type="submit" class="btn btn-primary" value="Create" />
        }

        <a asp-action="index" class="btn btn-primary">Index</a>

    </form>
</div>


@section Scripts
    {
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileLabel = $(this).next('.custom-file-input');
                var files = $(this)[0].files;
                if (files.length > 1) {
                    fileLabel.html(files.length + ' files selected');
                }
                else if (files.length == 1) {
                    fileLabel.html(files[0].name);
                }
            });
        });
    </script>
}

ShopTARge22/Views/RealEstates/Delete.cshtml
@model ShopTARge22.Models.RealEstates.RealEstateDeleteViewModel

<h1>Delete</h1>

<div>
    <h4>Spaceships</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="Address" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Address)
        </div>

        <div class="form-group row">
            <label asp-for="SizeSqrM" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.SizeSqrM)
        </div>

        <div class="form-group row">
            <label asp-for="RoomCount" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.RoomCount)
        </div>

        <div class="form-group row">
            <label asp-for="Floor" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Floor)
        </div>

        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.BuildingType)
        </div>

        <div class="form-group row">
            <label asp-for="BuiltInYear" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.BuiltInYear)
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.UpdatedAt)
        </div>
    </dl>

    @foreach (var images in Model.Image)
    {
        <partial name="_Images" model="images" />
    }

    <form asp-action="DeleteConfirmation">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" asp-controller="realEstates" class="btn btn-success">Back</a>
    </form>
</div>

ShopTARge22/Views/RealEstates/Details.cshtml
@model ShopTARge22.Models.RealEstates.RealEstateDetailsViewModel

<h1>Details</h1>

<div>
    <h4>Real Estates</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="Address" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Address)
        </div>

        <div class="form-group row">
            <label asp-for="SizeSqrM" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.SizeSqrM)
        </div>

        <div class="form-group row">
            <label asp-for="RoomCount" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.RoomCount)
        </div>

        <div class="form-group row">
            <label asp-for="Floor" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Floor)
        </div>

        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.BuildingType)
        </div>

        <div class="form-group row">
            <label asp-for="BuiltInYear" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.BuiltInYear)
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.UpdatedAt)
        </div>

        @foreach (var images in Model.Image)
        {
            <partial name="_Images" model="images" />
        }

    </dl>
    <a asp-action="Index" asp-controller="realEstates" class="btn btn-danger">Index</a>
</div>

ShopTARge22/Views/RealEstates/Index.cshtml
@model IEnumerable<ShopTARge22.Models.RealEstates.RealEstateIndexViewModel>

@{
    int rowNumber = 1;
}

<div>
    <a asp-action="create" asp-controller="RealEstates" type="submit" class="btn btn-primary">Create</a>
</div>


<div class="h1">
    RealEstates
</div>
<form method="post">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Address</th>
                <th scope="col">Building Type</th>
                <th scope="col">Room Count</th>
                <th scope="col">Size m2</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var realEstate in Model)
            {
                <tr>
                    <td>@rowNumber</td>
                    <td>@realEstate.Address</td>
                    <td>@realEstate.BuildingType</td>
                    <td>@realEstate.RoomCount</td>
                    <td>@realEstate.SizeSqrM</td>
                    <td>
                        <a asp-action="details" asp-controller="realestates" asp-route-id="@realEstate.Id" class="btn btn-info">Details</a>
                        <a asp-action="update" asp-controller="realestates" asp-route-id="@realEstate.Id" class="btn btn-primary">Update</a>
                        <a asp-action="delete" asp-controller="realestates" asp-route-id="@realEstate.Id" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>

                rowNumber += 1;
            }
        </tbody>
    </table>
</form>

ShopTARge22/Views/RealEstates/_Images.cshtml
@model ShopTARge22.Models.RealEstates.RealEstateImageViewModel

<div class="form-group row col-sm-4 offset-2">
    <div>@Model.ImageTitle</div>
    <img class="card-img-top" src="@Model.Image" asp-append-version="true" />
</div>