ShopTARge22/Models/Spaceships/ImageViewModel.cs
namespace ShopTARge22.Models.Spaceships
{
    public class ImageViewModel
    {
        public Guid ImageId { get; set; }
        public string FilePath { get; set; }
        public Guid SpaceshipId { get; set; }
    }
}

ShopTARge22/Models/Spaceships/SpaceshipCreateUpdateViewModel.cs
namespace ShopTARge22.Models.Spaceships
{
    public class SpaceshipCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public DateTime BuiltDate { get; set; }
        public int Passengers { get; set; }
        public int CargoWeight { get; set; }
        public int Crew { get; set; }
        public int EnginePower { get; set; }

        
        public DateTime CreatedAt { get; set; }
        public DateTime ModifiedAt { get; set; }

        public List<IFormFile> Files { get; set; }
        public List<ImageViewModel> Image { get; set; } 
            = new List<ImageViewModel>();
    }
}

ShopTARge22/Models/Spaceships/SpaceshipDeleteViewModel.cs
namespace ShopTARge22.Models.Spaceships
{
    public class SpaceshipDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public DateTime BuiltDate { get; set; }
        public int Passengers { get; set; }
        public int CargoWeight { get; set; }
        public int Crew { get; set; }
        public int EnginePower { get; set; }

        public List<ImageViewModel> ImageViewModels { get; set; } = new List<ImageViewModel>();


        public DateTime CreatedAt { get; set; }
        public DateTime ModifiedAt { get; set; }
    }
}

ShopTARge22/Models/Spaceships/SpaceshipDetailsViewModel.cs
namespace ShopTARge22.Models.Spaceships
{
    public class SpaceshipDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public DateTime BuiltDate { get; set; }
        public int Passengers { get; set; }
        public int CargoWeight { get; set; }
        public int Crew { get; set; }
        public int EnginePower { get; set; }

        public List<ImageViewModel> Image { get; set; } = new List<ImageViewModel>();

        public DateTime CreatedAt { get; set; }
        public DateTime ModifiedAt { get; set; }
    }
}

ShopTARge22/Models/Spaceships/SpaceshipsIndexViewModel.cs
namespace ShopTARge22.Models.Spaceships
{
    public class SpaceshipsIndexViewModel
    {
        public Guid? Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public DateTime BuiltDate { get; set; }
        public int Passengers { get; set; }
    }
}

ShopTARge22/Controllers/SpaceshipsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopTARge22.Core.Dto;
using ShopTARge22.Core.ServiceInterface;
using ShopTARge22.Data;
using ShopTARge22.Models.Spaceships;

namespace ShopTARge22.Controllers
{
    public class SpaceshipsController : Controller
    {
        private readonly ShopTARge22Context _context;
        private readonly ISpaceshipsServices _spaceshipServices;
        private readonly IFileServices _fileServices;

        public SpaceshipsController
            (
                ShopTARge22Context context,
                ISpaceshipsServices spaceshipsServices,
                IFileServices fileServices
            )
        {
            _context = context;
            _spaceshipServices = spaceshipsServices;
            _fileServices = fileServices;
        }


        public IActionResult Index()
        {
            var result = _context.Spaceships
                .Select(x => new SpaceshipsIndexViewModel
                {
                    Id = x.Id,
                    Name = x.Name,
                    Type = x.Type,
                    BuiltDate = x.BuiltDate,
                    Passengers = x.Passengers
                });

            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            SpaceshipCreateUpdateViewModel result = new SpaceshipCreateUpdateViewModel();

            return View("CreateUpdate", result);
        }

        [HttpPost]
        public async Task<IActionResult> Create(SpaceshipCreateUpdateViewModel vm)
        {
            var dto = new SpaceshipDto()
            {
                Id = vm.Id,
                Name = vm.Name,
                Type = vm.Type,
                Passengers = vm.Passengers,
                BuiltDate = vm.BuiltDate,
                CargoWeight = vm.CargoWeight,
                Crew = vm.Crew,
                EnginePower = vm.EnginePower,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
                Files = vm.Files,
                FileToApiDtos = vm.Image
                    .Select(x => new FileToApiDto
                    {
                        Id = x.ImageId,
                        ExistingFilePath = x.FilePath,
                        SpaceshipId = x.SpaceshipId,
                    }).ToArray()
            };

            var result = await _spaceshipServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var spaceship = await _spaceshipServices.DetailsAsync(id);

            if (spaceship == null)
            {
                return NotFound();
            }

            var images = await _context.FileToApis
                .Where(x => x.SpaceshipId == id)
                .Select(y => new ImageViewModel
                {
                    FilePath = y.ExistingFilePath,
                    ImageId = y.Id
                }).ToArrayAsync();


            var vm = new SpaceshipCreateUpdateViewModel();

            vm.Id = spaceship.Id;
            vm.Name = spaceship.Name;
            vm.Type = spaceship.Type;
            vm.BuiltDate = spaceship.BuiltDate;
            vm.Passengers = spaceship.Passengers;
            vm.CargoWeight = spaceship.CargoWeight;
            vm.Crew = spaceship.Crew;
            vm.EnginePower = spaceship.EnginePower;
            vm.CreatedAt = spaceship.CreatedAt;
            vm.ModifiedAt = spaceship.ModifiedAt;
            vm.Image.AddRange(images);


            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(SpaceshipCreateUpdateViewModel vm)
        {
            var dto = new SpaceshipDto()
            {
                Id = vm.Id,
                Name = vm.Name,
                Type = vm.Type,
                BuiltDate = vm.BuiltDate,
                Passengers = vm.Passengers,
                CargoWeight = vm.CargoWeight,
                Crew = vm.Crew,
                EnginePower = vm.EnginePower,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
                Files = vm.Files,
                FileToApiDtos = vm.Image
                    .Select(x => new FileToApiDto
                    {
                        Id = x.ImageId,
                        ExistingFilePath = x.FilePath,
                        SpaceshipId = x.SpaceshipId
                    }).ToArray()
            };

            var result = await _spaceshipServices.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var spaceship = await _spaceshipServices.DetailsAsync(id);

            if (spaceship == null)
            {
                return NotFound();
            }

            var images = await _context.FileToApis
                .Where(x => x.SpaceshipId == id)
                .Select(y => new ImageViewModel
                {
                    FilePath = y.ExistingFilePath,
                    ImageId = y.Id
                }).ToArrayAsync();

            var vm = new SpaceshipDetailsViewModel();

            vm.Id = spaceship.Id;
            vm.Name = spaceship.Name;
            vm.Type = spaceship.Type;
            vm.BuiltDate = spaceship.BuiltDate;
            vm.Passengers = spaceship.Passengers;
            vm.CargoWeight = spaceship.CargoWeight;
            vm.Crew = spaceship.Crew;
            vm.EnginePower = spaceship.EnginePower;
            vm.CreatedAt = spaceship.CreatedAt;
            vm.ModifiedAt = spaceship.ModifiedAt;
            vm.Image.AddRange(images);

            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var spaceship = await _spaceshipServices.DetailsAsync(id);

            if (spaceship == null)
            {
                return NotFound();
            }

            var images = await _context.FileToApis
                .Where(x => x.SpaceshipId == id)
                .Select(y => new ImageViewModel
                {
                    FilePath = y.ExistingFilePath,
                    ImageId = y.Id
                }).ToArrayAsync();

            var vm = new SpaceshipDeleteViewModel();

            vm.Id = spaceship.Id;
            vm.Name = spaceship.Name;
            vm.Type = spaceship.Type;
            vm.BuiltDate = spaceship.BuiltDate;
            vm.Passengers = spaceship.Passengers;
            vm.CargoWeight = spaceship.CargoWeight;
            vm.Crew = spaceship.Crew;
            vm.EnginePower = spaceship.EnginePower;
            vm.CreatedAt = spaceship.CreatedAt;
            vm.ModifiedAt = spaceship.ModifiedAt;
            vm.ImageViewModels.AddRange(images);

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var spaceshipId = await _spaceshipServices.Delete(id);

            if (spaceshipId == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> RemoveImage(ImageViewModel vm)
        {
            var dto = new FileToApiDto()
            {
                Id = vm.ImageId
            };

            var image = await _fileServices.RemoveImageFromApi(dto);

            if (image == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ShopTARge22/Views/Spaceships/CreateUpdate.cshtml
@model ShopTARge22.Models.Spaceships.SpaceshipCreateUpdateViewModel

@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Create</h1>
}


<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="ModifiedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Type" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Type" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="BuiltDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="BuiltDate" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Passengers" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Passengers" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="CargoWeight" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="CargoWeight" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Crew" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Crew" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="EnginePower" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="EnginePower" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Files" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-5">
                <div class="custom-file">
                    <input class="form-control custom-file-input" asp-for="Files" multiple type="file" />
                    <label class="custom-file-label">Choose file...</label>
                </div>
            </div>
        </div>
        <hr />

        <div>
            @foreach (var images in Model.Image)
            {
                <partial name="_Images" model="images" />
                <input asp-action="removeImage" asp-controller="spaceships" asp-route-imageId="@images.ImageId" type="submit" class="btn btn-danger" value="Remove Image" />
            }
        </div>
        <hr />
        @if(Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="spaceships" type="submit" class="btn btn-primary" value="Update" />
        }
        else
        {
            <input asp-action="create" asp-controller="spaceships" type="submit" class="btn btn-primary" value="Create" />
        }

        <a asp-action="index" class="btn btn-primary">Index</a>
    
    </form>
</div>


@section Scripts
{
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileLabel = $(this).next('.custom-file-input');
                var files = $(this)[0].files;
                if(files.length > 1 ) {
                    fileLabel.html(files.length + ' files selected');
                }
                else if (files.length == 1) {
                    fileLabel.html(files[0].name);
                }
            });
        });
    </script>
}

ShopTARge22/Views/Spaceships/Delete.cshtml
@model ShopTARge22.Models.Spaceships.SpaceshipDeleteViewModel

<h1>Delete</h1>

<div>
    <h4>Spaceships</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Name)
        </div>

        <div class="form-group row">
            <label asp-for="Type" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Type)
        </div>

        <div class="form-group row">
            <label asp-for="BuiltDate" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.BuiltDate)
        </div>

        <div class="form-group row">
            <label asp-for="Passengers" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Passengers)
        </div>

        <div class="form-group row">
            <label asp-for="CargoWeight" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CargoWeight)
        </div>

        <div class="form-group row">
            <label asp-for="Crew" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Crew)
        </div>

        <div class="form-group row">
            <label asp-for="EnginePower" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.EnginePower)
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ModifiedAt)
        </div>
    </dl>

    @foreach (var images in Model.ImageViewModels)
    {
        <partial name="_Images" model="images" />
    }
    
    <form asp-action="DeleteConfirmation">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" asp-controller="spaceships" class="btn btn-success">Back</a>
    </form>
</div>

ShopTARge22/Views/Spaceships/Details.cshtml
@model ShopTARge22.Models.Spaceships.SpaceshipDetailsViewModel

<h1>Details</h1>

<div>
    <h4>Spaceships</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Name)
        </div>

        <div class="form-group row">
            <label asp-for="Type" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Type)
        </div>

        <div class="form-group row">
            <label asp-for="BuiltDate" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.BuiltDate)
        </div>

        <div class="form-group row">
            <label asp-for="Passengers" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Passengers)
        </div>

        <div class="form-group row">
            <label asp-for="CargoWeight" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CargoWeight)
        </div>

        <div class="form-group row">
            <label asp-for="Crew" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Crew)
        </div>

        <div class="form-group row">
            <label asp-for="EnginePower" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.EnginePower)
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ModifiedAt)
        </div>

        @foreach (var images in Model.Image)
        {
            <partial name="_Images" model="images" />
        }

    </dl>
    <a asp-action="Index" asp-controller="spaceships" class="btn btn-danger">Back</a>
</div>

ShopTARge22/Views/Spaceships/Index.cshtml
@model IEnumerable<ShopTARge22.Models.Spaceships.SpaceshipsIndexViewModel>

@{
    int rowNumber = 1;
}

<div>
    <a asp-action="create" asp-controller="Spaceships" type="submit" class="btn btn-primary">Create</a>
</div>


<div class="h1">
    Products
</div>
<form method="post">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Name</th>
                <th scope="col">Type</th>
                <th scope="col">Built date</th>
                <th scope="col">Passengers</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var spaceships in Model)
            {
                <tr>
                    <td>@rowNumber</td>
                    <td>@spaceships.Name</td>
                    <td>@spaceships.Type</td>
                    <td>@spaceships.BuiltDate</td>
                    <td>@spaceships.Passengers</td>
                    <td>
                        <a asp-action="details" asp-controller="spaceships" asp-route-id="@spaceships.Id" class="btn btn-info">Details</a>
                        <a asp-action="update" asp-controller="spaceships" asp-route-id="@spaceships.Id" class="btn btn-primary">Update</a>
                        <a asp-action="delete" asp-controller="spaceships" asp-route-id="@spaceships.Id" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>

                rowNumber += 1;
            }
        </tbody>
    </table>
</form>

ShopTARge22/Views/Spaceships/_Images.cshtml
@model ShopTARge22.Models.Spaceships.ImageViewModel

@{
    var photoPaths = "~/multipleFileUpload/" + (Model.FilePath ?? "noimage.jpg");
}

<div class="form-group row col-sm-4 offset-2">
    <div>@Model.FilePath</div>
    <img class="card-img-top" src="@photoPaths" asp-append-version="true" />
</div>